export default [
  { label: 'Abukhaireni' },
  { label: 'Amlekhgunj' },
  { label: 'Argakhachi' },
  { label: 'Attariya' },
  { label: 'BANEPA' },
  { label: 'BANGLUNG' },
  { label: 'BARDAGHAT' },
  { label: 'BARDIBAS' },
  { label: 'BARDIYA' },
  { label: 'BELBARI' },
  { label: 'BENI' },
  { label: 'Besi Sahar / Lamjung' },
  { label: 'BHADRAPUR' },
  { label: 'BHAIRAHAWA' },
  { label: 'Bhaktapur' },
  { label: 'BIDUR (Nuwakot)' },
  { label: 'Biratchowk (Morang)' },
  { label: 'BIRATNAGAR' },
  { label: 'BIRGUNJ' },
  { label: 'BIRTAMOD' },
  { label: 'BUTWAL' },
  { label: 'Chandragadi / Jhapa' },
  { label: 'Chandrauta (kapilvastu)' },
  { label: 'CHAPUR' },
  { label: 'CHARIKOT' },
  { label: 'Dadeldhura' },
  { label: 'DALKEBAR' },
  { label: 'DAMAK' },
  { label: 'DAMAULI' },
  { label: 'DANG' },
  { label: 'Dhading' },
  { label: 'DHANGADHI' },
  { label: 'DHANKUTTA' },
  { label: 'DHARAN' },
  { label: 'DHULABARI' },
  { label: 'Dhulikhel' },
  { label: 'DIPAYAL' },
  { label: 'DUHABI' },
  { label: 'FIKKAL' },
  { label: 'GAIDAKOT' },
  { label: 'GAIGHAT' },
  { label: 'Ghorahi / Dang' },
  { label: 'GOL BAZAR' },
  { label: 'GORKHA' },
  { label: 'GOUR' },
  { label: 'GULERIYA' },
  { label: 'GULMI' },
  { label: 'Hariwon' },
  { label: 'HETAUDA' },
  { label: 'Hile Bazar' },
  { label: 'IILAM' },
  { label: 'INARUWA' },
  { label: 'ITAHARI' },
  { label: 'JALESWORE' },
  { label: 'JANAKPUR' },
  { label: 'Jeetpur (bara)' },
  { label: 'Jeetpur (kapilvastu)' },
  { label: 'KAKARVITA' },
  { label: 'KALAIYA' },
  { label: 'Katari (Udaypur)' },
  { label: 'KATHMANDU' },
  { label: 'Kawasoti (Nawalparasi)' },
  { label: 'KOHALPUR' },
  { label: 'KRISHNA NAGAR' },
  { label: 'Kushma / Parbat' },
  { label: 'LAHAN' },
  { label: 'Lalbandi' },
  { label: 'Lalitpur' },
  { label: 'Lamahi' },
  { label: 'Lamjung' },
  { label: 'LAMKI' },
  { label: 'Mahendranagar' },
  { label: 'Malangawa' },
  { label: 'MALEKHU' },
  { label: 'Manigram' },
  { label: 'Manthali (Ramechhap)' },
  { label: 'MIRCHIYA' },
  { label: 'MUNGLING' },
  { label: 'Narayanghat' },
  { label: 'NEPALGUNJ' },
  { label: 'NIJGADH' },
  { label: 'Palpa' },
  { label: 'PARASI' },
  { label: 'Parsa Bazar (Chitwan)' },
  { label: 'PATHARI' },
  { label: 'PATHLAYA' },
  { label: 'PHIDHIM' },
  { label: 'POKHARA' },
  { label: 'Pyuthan' },
  { label: 'RAJBIRAJ' },
  { label: 'RAXAUL' },
  { label: 'Sandikharka' },
  { label: 'SHYANJA' },
  { label: 'SIMRA / Bara' },
  { label: 'SINDHILI' },
  { label: 'SIRAHA' },
  { label: 'Sunali / Rupandehi' },
  { label: 'Sunwal / Rupandehi' },
  { label: 'SURANGA / Jhapa' },
  { label: 'SURKHET' },
  { label: 'Tamghas / Gulmi' },
  { label: 'TANDI / Chitwan' },
  { label: 'TANSEN / PALPA' },
  { label: 'TAPLEJUNG' },
  { label: 'Taulihawa / Kapilvastu' },
  { label: 'TIKAPUR / Kailali' },
  { label: 'TIRSHULI (nuwakot)' },
  { label: 'Tulsipur / Dang' },
  { label: 'URLABARI / Morang' },
];
